global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Jenkins metrics (requires Prometheus plugin)
  - job_name: 'jenkins'
    static_configs:
      - targets: ['jenkins:8080']
    metrics_path: '/prometheus'
    scrape_interval: 30s

  # SonarQube metrics (requires JMX exporter or web scraping)
  - job_name: 'sonarqube'
    static_configs:
      - targets: ['sonarqube:9000']
    metrics_path: '/api/monitoring/metrics'
    scrape_interval: 30s

  # Your Spring Boot application (when running)
  - job_name: 'spring-boot-app'
    static_configs:
      - targets: ['host.docker.internal:8080'] # Adjust port as needed
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s

  # Your Angular application metrics (if configured)
  - job_name: 'angular-app'
    static_configs:
      - targets: ['host.docker.internal:4200'] # Angular dev server
    scrape_interval: 30s